### PR TITLE
O3-1311: Initial setup of the project

### PR DESCRIPTION
**Pull request by anjula-sack**
## Purpose

- The purpose of this PR is to fix #[O3-1311](https://issues.openmrs.org/browse/O3-1311)

## Goals

- Remove the boilerplate code from the esm-template app and change it according to the cohort builder

## Approach

- Removed the boilerplate code
- Renamed the template

## Screenshots
Screenshot 2022-06-18 at 2 16 01 PM

### CODE REVIEW

**Comment by jayasanka-sack** [comment]
Good job @anjula-sack !
The UI is a bit different from the mockup, is it something that you are planning to fix on your next PR? (white bg etc.)

**Comment by anjula-sack** [comment]
> Good job @anjula-sack ! The UI is a bit different from the mockup, is it something that you are planning to fix on your next PR? (white bg etc.)

yes it's a part of the next ticket.  Here's the current state of that.
image

**Comment by jayasanka-sack** [comment]
Amazing! 

Quick suggestion: Shall we change the bg colour to white as provided in the mockup? (in the next PR)

**Review by jayasanka-sack — APPROVED** [review]
Thanks @anjula-sack !

**Comment by anjula-sack** [comment]
> Amazing!
> 
> Quick suggestion: Shall we change the bg colour to white as provided in the mockup? (in the next PR)

sure

**Pull request merged**
